export let shopData = {
  // product_value : soldOut, md, best, sale, hot
  slingBag: [
    {
      id: 0,
      product_Name: "쉴드백 SHIELD BAG",
      product_Price: "159,000원",
      product_value: [],
    },
    {
      id: 1,
      product_Name: "REO714 슬링백",
      product_Price: "119,000원",
      product_value: ["best", "md"],
    },
    {
      id: 2,
      product_Name: "REO831 쓰리웨이백",
      product_Price: "150,000원",
      product_value: [],
    },
    {
      id: 3,
      product_Name: "방화복 핸드폰 가방",
      product_Price: "52,000원",
      product_value: ["md"],
    },
    {
      id: 4,
      product_Name: "핸드폰 가방 블랙",
      product_Price: "42,000원",
      product_value: [],
    },
    {
      id: 5,
      product_Name: "히어로 샤코슈백",
      product_Price: "53,910원",
      product_value: ["sale"],
    },
    {
      id: 6,
      product_Name: "REO Z Bag",
      product_Price: "29,000원",
      product_value: ["soldOut"],
    },
    {
      id: 7,
      product_Name: "소방호스 미니 크로스백",
      product_Price: "62,000원",
      product_value: ["best", "md"],
    },
    {
      id: 8,
      product_Name: "미니 크로스백 블랙",
      product_Price: "62,000원",
      product_value: [],
    },
  ],
  pouch: [
    {
      id: 0,
      product_Name: "소방호스 카드지갑 M",
      product_Price: "28,000원",
      product_value: ["md"],
    },
    {
      id: 1,
      product_Name: "소방호스 카드지갑 S",
      product_Price: "22,000원",
      product_value: ["best"],
    },
    {
      id: 2,
      product_Name: "소방호스 필통",
      product_Price: "26,000원",
      product_value: [],
    },
    {
      id: 3,
      product_Name: "REO Z Bag",
      product_Price: "29,000원",
      product_value: ["soldOut"],
    },
    {
      id: 4,
      product_Name: "풉백",
      product_Price: "22,000원",
      product_value: [],
    },
    {
      id: 5,
      product_Name: "당근파우치",
      product_Price: "9,000원",
      product_value: [],
    },
    {
      id: 6,
      product_Name: "볼드 명함지갑",
      product_Price: "72,000원",
      product_value: ["best"],
    },
    {
      id: 7,
      product_Name: "볼드 카드지갑",
      product_Price: "42,000원",
      product_value: ["best"],
    },
    {
      id: 8,
      product_Name: "미니 파우치",
      product_Price: "15,000원",
      product_value: [],
    },
    {
      id: 9,
      product_Name: "REO521 노트북파우치",
      product_Price: "64,000원",
      product_value: ["soldOut"],
    },
    {
      id: 10,
      product_Name: "방화복 명함지갑",
      product_Price: "58,000원",
      product_value: ["best", "md"],
    },
    {
      id: 11,
      product_Name: "방화복 다이어리 세트",
      product_Price: "49,700원",
      product_value: ["sale"],
    },
  ],
  keyRing: [
    {
      id: 0,
      product_Name: "행운의 뱀",
      product_Price: "19,900원",
      product_value: ["sale"],
    },
    {
      id: 1,
      product_Name: "심전도 키링",
      product_Price: "15,000원",
      product_value: ["best", "md"],
    },
    {
      id: 2,
      product_Name: "119 키홀더",
      product_Price: "11,900원",
      product_value: [],
    },
    {
      id: 3,
      product_Name: "풉백",
      product_Price: "22,000원",
      product_value: [],
    },
    {
      id: 4,
      product_Name: "소방관 피규어키링",
      product_Price: "10,710원",
      product_value: [],
    },
    {
      id: 5,
      product_Name: "영웅의 집 키링",
      product_Price: "25,000원",
      product_value: ["best", "md"],
    },
    {
      id: 6,
      product_Name: "소방벌 키링",
      product_Price: "22,000원",
      product_value: ["hot"],
    },
    {
      id: 7,
      product_Name: "돌고래 키링",
      product_Price: "31,000원",
      product_value: ["best", "hot"],
    },
    {
      id: 8,
      product_Name: "유니콘 키링",
      product_Price: "31,000원",
      product_value: [],
    },
  ],
  bracelet: [
    {
      id: 0,
      product_Name: "당근팔찌",
      product_Price: "22,000원",
      product_value: [],
    },
    {
      id: 1,
      product_Name: "카라비너 네온팔찌",
      product_Price: "16,000원",
      product_value: [],
    },
    {
      id: 2,
      product_Name: "카라비너 팔찌",
      product_Price: "19,000원",
      product_value: ["best", "hot"],
    },
    {
      id: 3,
      product_Name: "방화복 팔찌",
      product_Price: "22,000원",
      product_value: [],
    },
  ],
  toteBag: [
    {
      id: 0,
      product_Name: "플라이백 라지",
      product_Price: "220,000원",
      product_value: [],
    },
    {
      id: 1,
      product_Name: "플라이백 레귤러",
      product_Price: "167,000원",
      product_value: ["md"],
    },
    {
      id: 2,
      product_Name: "플라이백 쁘띠",
      product_Price: "162,000원",
      product_value: [],
    },
    {
      id: 3,
      product_Name: "REO831 쓰리웨이백",
      product_Price: "150,000원",
      product_value: [],
    },
    {
      id: 4,
      product_Name: "REO89 토트백",
      product_Price: "220,000원",
      product_value: ["best", "md"],
    },
    {
      id: 5,
      product_Name: "레토백",
      product_Price: "67,000원",
      product_value: [],
    },
    {
      id: 6,
      product_Name: "레코백 세트",
      product_Price: "50,000원",
      product_value: ["sale"],
    },
    {
      id: 7,
      product_Name: "레코백",
      product_Price: "44,000원",
      product_value: [],
    },
    {
      id: 8,
      product_Name: "볼드백",
      product_Price: "102,000원",
      product_value: [],
    },
  ],
};
